hermesmvc/Models/FixedTE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedTE
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int year { get; set; }
        public int segment_id { get; set; }
        public int fixedte_item_id { get; set; }
        public double value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual FixedTE_details FixedTE_details { get; set; }
    }
}

hermesmvc/Models/FixedTE_types.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedTE_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedTE_types()
        {
            this.FixedTE_details = new HashSet<FixedTE_details>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedTE_details> FixedTE_details { get; set; }
    }
}

hermesmvc/ViewModels/FixedTEViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace hermesmvc.ViewModels
{
    public class FixedTEViewModel
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public int year { get; set; }
        public int segment_id { get; set; }
        public string segment_name { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}")]
        public double On_invoice { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}")]
        public double Off_invoice { get; set; }

        public double ToNIV { get { return (1-On_invoice); } }
        public double ToNSV { get { return (1 - On_invoice)*(1-Off_invoice); } }
    }
}

hermesmvc/Controllers/FixedTEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using hermesmvc.Models;
using hermesmvc.ViewModels;

namespace hermesmvc.Controllers
{
    public class FixedTEsController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            //test comment
            var getcustomerlist = db.Customers.ToList();
            getcustomerlist.Insert(0, new Customer { name = "All", id = 0 });
            SelectList list_customer = new SelectList(getcustomerlist, "id", "name");              
            ViewBag.CustomerListName = list_customer;

            var getsegmentlist = db.Segments.ToList();
            getsegmentlist.Insert(0, new Segment { name = "All", id = 0 });
            SelectList list_segment = new SelectList(getsegmentlist, "id", "name");
            ViewBag.SegmentListName = list_segment;

            var getyearlist = db.Years.ToList();
            SelectList list_year = new SelectList(getyearlist, "id", "name");
            ViewBag.YearListName = list_year;

            List<FixedTEViewModel> FixedTElist = new List<FixedTEViewModel>();

            var fixedTEs = db.FixedTEs
                        .OrderBy(m => m.segment_id)
                        .GroupBy(m => new {  m.year,  m.Segment, m.Customer }) //m.FixedTE_details.FixedTE_types,
                        .Select(g => new {
                            segment_id = g.Key.Segment.id,
                            segment_name = g.Key.Segment.name,
                            customer_id = g.Key.Customer.id,
                            customer_name = g.Key.Customer.name,
                            year = g.Key.year,
                            value = g.Sum(x => x.value),
                            on_invoice = g.Sum(x => x.FixedTE_details.FixedTE_types.id == 1 ? x.value : 0),
                            off_invoice = g.Sum(x => x.FixedTE_details.FixedTE_types.id == 2 ? x.value : 0)
                        });

            foreach (var item in fixedTEs)
            {
                if (item.year == DateTime.Now.Year)
                {
                    FixedTEViewModel FixedTEvm = new FixedTEViewModel();
                    FixedTEvm.customer_id = item.customer_id;
                    FixedTEvm.customer_name = item.customer_name;
                    FixedTEvm.segment_id = item.segment_id;
                    FixedTEvm.segment_name = item.segment_name;
                    FixedTEvm.year = item.year;
                    FixedTEvm.On_invoice = item.on_invoice;
                    FixedTEvm.Off_invoice = item.off_invoice;
                    FixedTElist.Add(FixedTEvm);
                }   
            }

            return View(FixedTElist);   
            

        }

        [HttpPost]
        public ActionResult Index(FixedTE FTE, FormCollection form)
        {
            var getcustomerlist = db.Customers.ToList();
            getcustomerlist.Insert(0, new Customer { name = "All", id = 0 });
            SelectList list_customer = new SelectList(getcustomerlist, "id", "name");
            ViewBag.CustomerListName = list_customer;

            var getsegmentlist = db.Segments.ToList();
            getsegmentlist.Insert(0, new Segment { name = "All", id = 0 });
            SelectList list_segment = new SelectList(getsegmentlist, "id", "name");
            ViewBag.SegmentListName = list_segment;

            var getyearlist = db.Years.ToList();
            SelectList list_year = new SelectList(getyearlist, "id", "name");
            ViewBag.YearListName = list_year;


            //var fixedTEs = db.FixedTEs.Include(f => f.Customer).Include(f => f.Segment).Include(f => f.FixedTE_details);
            //var fixedTEs = db.FixedTEs.Include(f => f.Customer).Include(f => f.FixedTE_details);

            //if (form["CustomerList"] != null && form["SegmentList"] != null)
            //if (form["CustomerList"] != null)
            //{
            //    int intDDL_Customer = Convert.ToInt32(form["CustomerList"].ToString());
            //int intDDL_Segment = Convert.ToInt32(form["SegmentList"].ToString());
            //fixedTEs = db.FixedTEs.Include(f => f.Customer).Include(f => f.Segment).Include(f => f.FixedTE_details).Where(f => f.customer_id == intDDL_Customer).Where(f => f.segment_id == intDDL_Segment);
            //    fixedTEs = db.FixedTEs.Include(f => f.Customer).Include(f => f.FixedTE_details).Where(f => f.customer_id == intDDL_Customer);
            //}

            //return View(fixedTEs.ToList());

            List<FixedTEViewModel> FixedTElist = new List<FixedTEViewModel>();

            int intDDL_Customer = Convert.ToInt32(form["CustomerList"].ToString());
            int intDDL_Segment = Convert.ToInt32(form["SegmentList"].ToString());
            int intDDL_Year = Convert.ToInt32(form["YearList"].ToString());
            intDDL_Year = getyearlist[intDDL_Year - 1].name;

            var fixedTEs = db.FixedTEs
                        .OrderBy(m => m.segment_id)
                        .GroupBy(m => new { m.year, m.Segment, m.Customer }) //m.FixedTE_details.FixedTE_types,
                        .Select(g => new {
                            segment_id = g.Key.Segment.id,
                            segment_name = g.Key.Segment.name,
                            customer_id = g.Key.Customer.id,
                            customer_name = g.Key.Customer.name,
                            year = g.Key.year,
                            value = g.Sum(x => x.value),
                            on_invoice = g.Sum(x => x.FixedTE_details.FixedTE_types.id == 1 ? x.value : 0),
                            off_invoice = g.Sum(x => x.FixedTE_details.FixedTE_types.id == 2 ? x.value : 0)
                        });

            // take a searched fixedTEs values from db
            if (intDDL_Customer == 0 && intDDL_Segment == 0)
            {
                foreach (var item in fixedTEs)
                {
                    if (item.year == intDDL_Year)
                    {
                        FixedTEViewModel FixedTEvm = new FixedTEViewModel();
                        FixedTEvm.customer_id = item.customer_id;
                        FixedTEvm.customer_name = item.customer_name;
                        FixedTEvm.segment_id = item.segment_id;
                        FixedTEvm.segment_name = item.segment_name;
                        FixedTEvm.year = item.year;
                        FixedTEvm.On_invoice = item.on_invoice;
                        FixedTEvm.Off_invoice = item.off_invoice;
                        FixedTElist.Add(FixedTEvm);
                    }
                }

                return View(FixedTElist);
            }  
            else if (intDDL_Customer == 0)
            {
                foreach (var item in fixedTEs)
                {
                    if (item.segment_id == intDDL_Segment && item.year == intDDL_Year)
                    {
                        FixedTEViewModel FixedTEvm = new FixedTEViewModel();
                        FixedTEvm.customer_id = item.customer_id;
                        FixedTEvm.customer_name = item.customer_name;
                        FixedTEvm.segment_id = item.segment_id;
                        FixedTEvm.segment_name = item.segment_name;
                        FixedTEvm.year = item.year;
                        FixedTEvm.On_invoice = item.on_invoice;
                        FixedTEvm.Off_invoice = item.off_invoice;
                        FixedTElist.Add(FixedTEvm);
                    }
                }
            }
            else if (intDDL_Segment == 0)
            {
                foreach (var item in fixedTEs)
                {
                    if (item.customer_id == intDDL_Customer && item.year == intDDL_Year)
                    {
                        FixedTEViewModel FixedTEvm = new FixedTEViewModel();
                        FixedTEvm.customer_id = item.customer_id;
                        FixedTEvm.customer_name = item.customer_name;
                        FixedTEvm.segment_id = item.segment_id;
                        FixedTEvm.segment_name = item.segment_name;
                        FixedTEvm.year = item.year;
                        FixedTEvm.On_invoice = item.on_invoice;
                        FixedTEvm.Off_invoice = item.off_invoice;
                        FixedTElist.Add(FixedTEvm);
                    }
                }
            }
            else
            {
                foreach (var item in fixedTEs)
                {
                    if (item.customer_id == intDDL_Customer && item.segment_id == intDDL_Segment && item.year == intDDL_Year)
                    {
                        FixedTEViewModel FixedTEvm = new FixedTEViewModel();
                        FixedTEvm.customer_id = item.customer_id;
                        FixedTEvm.customer_name = item.customer_name;
                        FixedTEvm.segment_id = item.segment_id;
                        FixedTEvm.segment_name = item.segment_name;
                        FixedTEvm.year = item.year;
                        FixedTEvm.On_invoice = item.on_invoice;
                        FixedTEvm.Off_invoice = item.off_invoice;
                        FixedTElist.Add(FixedTEvm);
                    }
                }
            }


            

            return View(FixedTElist);

        }

        public ActionResult Test2()
        {

            List<FixedTEViewModel> FixedTElist = new List<FixedTEViewModel>();

            /* works
            var fixedTEs = db.FixedTEs
                                    .OrderBy(m => m.Segment.name);
            */


            /* does not work
            var fixedTEs = db.FixedTEs
                                    .OrderBy(m => m.segment_id)
                                    .GroupBy(m => new { m.segment_id, m.customer_id, m.year })

hermesmvc/Views/FixedTEs/Create.cshtml
@model hermesmvc.Models.FixedTE

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FixedTE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.customer_id, "customer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("customer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.customer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.segment_id, "segment_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("segment_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.segment_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fixedte_item_id, "fixedte_item_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fixedte_item_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fixedte_item_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

hermesmvc/Views/FixedTEs/Delete.cshtml
@model hermesmvc.Models.FixedTE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FixedTE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Segment.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Segment.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixedTE_details.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixedTE_details.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

hermesmvc/Views/FixedTEs/Details.cshtml
@model hermesmvc.Models.FixedTE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FixedTE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Segment.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Segment.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixedTE_details.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixedTE_details.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

hermesmvc/Views/FixedTEs/Edit.cshtml
@model hermesmvc.Models.FixedTE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FixedTE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.customer_id, "customer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("customer_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.customer_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.segment_id, "segment_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("segment_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.segment_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fixedte_item_id, "fixedte_item_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fixedte_item_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fixedte_item_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

hermesmvc/Views/FixedTEs/Index.cshtml
@model IEnumerable<hermesmvc.ViewModels.FixedTEViewModel>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>

    @using (Html.BeginForm("Index", "FixedTEs", FormMethod.Post))
    {
        @Html.DropDownList("CustomerList", ViewBag.CustomerListName as SelectList)
        @Html.DropDownList("SegmentList", ViewBag.SegmentListName as SelectList)
        @Html.DropDownList("YearList", ViewBag.YearListName as SelectList)

        <input id="Submit1" type="submit" value="search" />

    }
</p>

<table class="table">

    <tr>
        <th>
            Year
        </th>
        <th>
            Customer
        </th>
        <th>
            Segment
        </th>
        <th>
            ON invoice
        </th>
        <th>
            OFF invoice
        </th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.customer_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.segment_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.On_invoice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Off_invoice)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.customer_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.customer_id })
            </td>
        </tr>
    }

</table>

hermesmvc/Views/FixedTEs/Index_init.cshtml
@model IEnumerable<hermesmvc.Models.FixedTE>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.name)
        </th>
            <th>
                @Html.DisplayNameFor(model => model.Segment.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FixedTE_details.name)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Segment.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FixedTE_details.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }

    </table>

hermesmvc/Views/FixedTEs/Index_test.cshtml
@model IEnumerable<hermesmvc.Models.FixedTE>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>

    @using (Html.BeginForm("Index", "FixedTEs", FormMethod.Post))
    {
        @Html.DropDownList("CustomerList", ViewBag.CustomerListName as SelectList)
        @Html.DropDownList("SegmentList", ViewBag.SegmentListName as SelectList)


        <input id="Submit1" type="submit" value="search" />

    }
</p>



            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.year)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.value)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Customer.name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Segment.name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FixedTE_details.name)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.year)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.value)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Customer.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Segment.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FixedTE_details.name)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </td>
                    </tr>
                }

            </table>

hermesmvc/Views/FixedTEs/Test2.cshtml
@model IEnumerable<hermesmvc.Models.FixedTE>

@{
    ViewBag.Title = "Test2";
}

<h2>Test2</h2>


<table class="table">

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.year)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.segment_id)
        </td>


    </tr>
}

</table>